"""initial intelligence schemas

Revision ID: 3f22f0c7a623
Revises: 
Create Date: 2026-07-13 21:19:45.919438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f22f0c7a623'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True),
    sa.Column('tokens_completion', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('prompt_snippet', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_costs_id'), 'ai_costs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_costs_model_name'), 'ai_costs', ['model_name'], unique=False)
    op.create_index(op.f('ix_ai_costs_timestamp'), 'ai_costs', ['timestamp'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('state', sa.Enum('DISCOVERED', 'VALIDATING', 'HIGH_DEMAND', 'CONTENT_READY', 'COVERED', 'DORMANT', 'SEASONAL_RETURN', name='problemstate'), nullable=True),
    sa.Column('seasonality', sa.String(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('visual_proof', sa.Boolean(), nullable=True),
    sa.Column('evergreen_score', sa.Float(), nullable=True),
    sa.Column('related_products', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('videos_published_dates', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('can_publish_again', sa.String(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_index(op.f('ix_problems_name'), 'problems', ['name'], unique=True)
    op.create_index(op.f('ix_problems_state'), 'problems', ['state'], unique=False)
    op.create_table('raw_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('rss_xml', sa.Text(), nullable=True),
    sa.Column('json_payload', sa.JSON(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('connector_version', sa.String(), nullable=True),
    sa.Column('rss_guid', sa.String(), nullable=True),
    sa.Column('feed_url', sa.String(), nullable=True),
    sa.Column('doc_hash', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_documents_doc_hash'), 'raw_documents', ['doc_hash'], unique=False)
    op.create_index(op.f('ix_raw_documents_id'), 'raw_documents', ['id'], unique=False)
    op.create_index(op.f('ix_raw_documents_source_name'), 'raw_documents', ['source_name'], unique=False)
    op.create_index(op.f('ix_raw_documents_url'), 'raw_documents', ['url'], unique=False)
    op.create_table('source_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('connector_type', sa.Enum('OFFICIAL', 'TREND', 'COMMUNITY', 'MEDIA', name='connectortype'), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('romanian_relevance', sa.Float(), nullable=False),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('update_frequency', sa.String(), nullable=True),
    sa.Column('expected_latency', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('api_available', sa.Boolean(), nullable=True),
    sa.Column('rate_limits', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_profiles_connector_type'), 'source_profiles', ['connector_type'], unique=False)
    op.create_index(op.f('ix_source_profiles_id'), 'source_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_source_profiles_name'), 'source_profiles', ['name'], unique=True)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'WATCHING', 'READY', 'APPROVED', 'REJECTED', 'ARCHIVED', 'PUBLISHED', name='opportunitystatus'), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('why_not', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('missing_evidence', sa.Text(), nullable=True),
    sa.Column('risk_if_wrong', sa.Text(), nullable=True),
    sa.Column('roi_impact', sa.Float(), nullable=True),
    sa.Column('roi_trust', sa.Float(), nullable=True),
    sa.Column('roi_demand', sa.Float(), nullable=True),
    sa.Column('roi_production_ease', sa.Float(), nullable=True),
    sa.Column('roi_total', sa.Float(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('production_time_min', sa.Integer(), nullable=True),
    sa.Column('editing_time_min', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('avg_watch_time_sec', sa.Integer(), nullable=True),
    sa.Column('retention_percent', sa.Float(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('would_produce_again', sa.Boolean(), nullable=True),
    sa.Column('best_hook', sa.Text(), nullable=True),
    sa.Column('worst_mistake', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id')
    )
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('freshness', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_document_id', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_source_name'), 'signals', ['source_name'], unique=False)
    op.create_index(op.f('ix_signals_url'), 'signals', ['url'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('film_decision', sa.Boolean(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('confidence_percentage', sa.Float(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('reasons_against', sa.Text(), nullable=True),
    sa.Column('estimated_filming_min', sa.Integer(), nullable=True),
    sa.Column('erik_decision', sa.Enum('PENDING', 'APPROVE', 'REJECT', 'POSTPONE', 'ARCHIVE', name='humandecision'), nullable=True),
    sa.Column('erik_notes', sa.Text(), nullable=True),
    sa.Column('date_generated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_index(op.f('ix_recommendations_erik_decision'), 'recommendations', ['erik_decision'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_erik_decision'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_signals_url'), table_name='signals')
    op.drop_index(op.f('ix_signals_source_name'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_source_profiles_name'), table_name='source_profiles')
    op.drop_index(op.f('ix_source_profiles_id'), table_name='source_profiles')
    op.drop_index(op.f('ix_source_profiles_connector_type'), table_name='source_profiles')
    op.drop_table('source_profiles')
    op.drop_index(op.f('ix_raw_documents_url'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_source_name'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_id'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_doc_hash'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_problems_state'), table_name='problems')
    op.drop_index(op.f('ix_problems_name'), table_name='problems')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_ai_costs_timestamp'), table_name='ai_costs')
    op.drop_index(op.f('ix_ai_costs_model_name'), table_name='ai_costs')
    op.drop_index(op.f('ix_ai_costs_id'), table_name='ai_costs')
    op.drop_table('ai_costs')
    # ### end Alembic commands ###
